version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /C:\Users\rainier.pena\Desktop\docker-django
    ports:
      - "8000:8000"
    depends_on:
      - db

